<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Phalcon PHP Framework</title>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/js/bootstrapV3-datetimepicker/bootstrap-datetimepicker.min.css" />
    <link rel="stylesheet" href="/js/jasny-bootstrap/css/jasny-bootstrap.min.css" />
    <link rel="stylesheet" href="/css/style.css" />
    
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="/js/bootstrapV3-datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <script src="/js/jasny-bootstrap/js/jasny-bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Trip2p</a>
            </div>
        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Viewer <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/list.html">Result(list and search)</a></li>
                    <li class="divider"></li>
                    <li><a href="/tour.html">Tours</a></li>
                    <li><a href="/expert.html">Expert Page</a></li>
                    <li class="divider"></li>
                    <li><a href="/request.html">Reuest</a></li>
                    <li><a href="/request-confirm.html">Reuest Confirm</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Experter <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/build-qiuck.html?step=1">Quickly Info building</a></li>
                    <li><a href="/build-qiuck.html?step=2">Detail Info building</a></li>
                    <li class="divider"></li>
                    <li><a href="/build-account.html">Account Building</a></li>
                    <li><a href="/build-account.html?withfb=1">Account Building with FB</a></li>
                    <li><a href="/build-preview.html">Preview Page</a></li>
                  </ul>
                </li>
              </ul>
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Find Tours">
                </div>
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-search"></i>
                </button>
              </form>
              
              <div class="nav navbar-form navbar-right">
                  <a class="btn btn-sm btn-primary" href="/login.html">Login</a>
                  <a class="btn btn-sm btn-primary" href="/signup.html">Sign up</a>
                  <span class="dropdown">
                  <a class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" href="#">
                     <i class="fa fa-user">&nbsp;</i> Username <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/profile.html">My Page</a></li>
                    <li><a href="/history.html">History</a></li>
                    <li><a href="/logout.html">Logout</a></li>
                  </ul>
                  </span>
              </div>
              
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </header>
    
    <div class="container" style="min-height: 500px;">
    <?=$this->partial( $page );?>
    </div>
    
    <hr />
    <footer class="container-fluid">
    <div class="row">
        <div class="col-xs-6 col-sm-4 text-left">
            <img class="img" src="http://placehold.it/160x75/3461A1&text=Trip2p" />
        </div>    
        <div class="col-xs-6 col-sm-8 text-right">&copy; 2014 personalwork.tw</div>
    </div>
    </footer>
    
    
</body>
</html>