<div class="container">

    <div class="page-header text-center">
        <h1>Be a Local Expert</h1>
        <h4 class="page-subtitle">as a guide and meet some friends!</h4>
    </div>
    
        <form class="form-horizontal" id="" role="form">
            
    <div class="row" style="position: relative;">
            <div class="col-sm-3 col-md-2 fileinput fileinput-new" data-provides="fileinput" data-name="avatar">
                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                <img src="http://placehold.it/200x200&text=Avatar" />
                </div>
                  <div class="text-center">
                    <span class="btn btn-default btn-file">
                        <span class="fileinput-new">選擇</span>
                        <span class="fileinput-exists">變更</span> <input type="file" name="avatar" />
                    </span>
                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">移除</a>
                  </div>
            </div>
            
            <div class="col-sm-9 col-md-10">
            <div class="form-group" style="margin-top:1.6em;margin-bottom:1.6em;">
                <label class="col-sm-3 control-label" for="email">E-mail</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control" id="email" name="email" />
                </div>
            </div>
            <div class="form-group" style="margin-top:1.6em;margin-bottom:1.6em;">
                <label class="col-sm-3 control-label" for="email">Password</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="password" name="password" />
                </div>
            </div>
            <div class="form-group" style="margin-top:1.6em;margin-bottom:2em;">
                <label class="col-sm-3 control-label" for="email">Check password</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="password2" name="password2" />
                </div>
            </div>
            
            <div class="text-center" style="background-color:#3461A1;position: absolute; top:0px; right:0px; height:190px;">
                <p class="lead">Sign up with Facebook account</p>
                <a class="btn btn-primary btn-lg" href="#">Facebook</a>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label" for="email">Name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="firstname" name="firstname" />
                </div>
                <div class="col-sm-1 text-center" style="padding-top:10px;">
                <i class="fa fa-comment"></i>
                </div>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="lastname" name="lastname" />
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label" for="email">Languages</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" id="firstname" name="firstname" />
                </div>
                <div class="col-sm-1 text-center" style="padding-top:10px;">
                <i class="fa fa-comment"></i>
                </div>
                <div class="col-sm-2">
                    <input type="text" class="form-control" id="lastname" name="lastname" />
                </div>
                <div class="col-sm-1 text-center" style="padding-top:10px;">
                <i class="fa fa-comment"></i>
                </div>
                <div class="col-sm-2">
                    <input type="text" class="form-control" id="lastname" name="lastname" />
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label" for="occupation">Occupation</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" id="occupation" name="occupation" />
                </div>
                <label class="col-sm-2 control-label" for="city">City</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" id="city" name="city" />
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label" for="interests">Interests</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" id="interests" name="interests" />
                </div>
                <label class="col-sm-2 control-label" for="cell">Cell</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" id="cell" name="cell" />
                </div>
            </div>            
            
            <div class="form-group">
                <label class="col-sm-3 control-label" for="biography">Biography</label>
                <div class="col-sm-9">
                    <textarea id="biography" name="biography" class="form-control" rows="8"></textarea>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Passport</label>
                <div class="col-sm-9 fileinput fileinput-new" data-provides="fileinput" data-name="passport">
                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 700px; height: 240px;">
                    <img src="http://placehold.it/700x240&text=Passport" />
                    </div>
                      <div class="text-center">
                        <span class="btn btn-default btn-file">
                            <span class="fileinput-new">選擇</span>
                            <span class="fileinput-exists">變更</span> <input type="file" name="passport" />
                        </span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">移除</a>
                      </div>
                </div>
            </div>

            </div>
    </div>
    <div>
        
    </div>
        
          <div class="form-group">
            <div class="col-xs-12 text-right">
              <button type="button" class="btn btn-primary" onclick="alert('server-side!');">Submit</button>
            </div>
          </div>
            
        </form>
        
    

</div>
