<style type="text/css">
    .feature{ position: relative; }
    .feature-img{ width: inherit; min-height:200px; max-height: 480px; }
    .feature-expert{ 
        position: absolute;
        bottom: -90px;
        left: 30px;
    }
    
    .tour-name{
        margin-left:5em;
        margin-top:-10px;
    }
    
    .tour-name span{
        margin-left:3em;
        font-size: 0.4em;
    }
    
    .table-fix-border tr td{ border:none !important; }
    .tour-field-title{
        font-size: 2em;
        color:#969696;
    }
    
    .tour-eminfo{
        position:relative;
        top:15px;
        left:10px;
        z-index:50;
        background-color: #333;
        width: 110%;
        height: 120px;
        color: #FFF;
        font-size: 2.5em;
        padding-left:10px;
    }
        .eminfo-desc{ font-size: 0.7em; margin-right:25px; }
        .eminfo-price{ font-size: 1.2em;}
    
    .thumb-control{
        bottom: 0px;
        left:0px; 
    }    
</style>

<div class="container">

    <section class="feature feature-img" >
        <img class="img-rounded img-responsive" src="http://placehold.it/1200x480" alt="1200x480" />
        <div class="text-right">
            <i class="fa fa-facebook"></i> Howie Young and 7 other friends also saved this tour
        </div>
        <div class="feature-expert">
            <img src="http://placehold.it/120x150/285E8E" />
            <h4 class="text-center">Howie young</h4>
        </div>
    </section>
    
    <section class="row" style="margin: 20px auto;">
        <h1 class="tour-name">
            Ximen Urban tour
            <span>
                <i class="fa fa-map-marker"></i> Da-An dirstict, Shin-Yi dirstict
            </span>
        </h1>
        
        <table class="table table-fix-border" style="clear:both; margin-top:20px;">
            <tr>
                <td width="20%" style="padding-bottom: 15px;">
                    <h4 class="tour-field-title">Occupation</h4>
                    <p>Restaurant Owner</p>
                </td>
                <td colspan="2" width="27%">
                    <h4 class="tour-field-title">Language</h4>
                    <p>English / Chinese / Japanese</p>
                </td>
                <td colspan="2" width="27%">
                    <h4 class="tour-field-title">Interests</h4>
                    <p>Photograph / Visual Design / Jog</p>
                </td>
                <td rowspan="2" width="26%" style="border:1px #000 solid !important;">
                    <div class="tour-eminfo">
                        Ximen Urban tour<br />
                        <span class="eminfo-desc pull-right">for <b>USD</b> <span class="eminfo-price">$30</span></span>
                    </div>
                    <div style="margin-top:20px;" >
                    <button class="btn btn-default btn-lg" style="margin-left:1%; width:48%;">xx</button>
                    <button class="btn btn-default btn-lg" style="width:48%;">xx</button>
                    </div>
                    <div style="margin-top:10px;" >
                    <button class="btn btn-default btn-lg" style="margin-left:1%; width:48%;">xx</button>
                    <button class="btn btn-default btn-lg" style="width:48%;">xx</button>
                    </div>
                </td>
            </tr>
            <tr style="border-bottom: 1px #CCC solid;">
                <td style="padding-bottom: 30px;">
                    <h4 class="tour-field-title">Activities</h4>
                    <p>
                        <i class="fa fa-camera fa-4x"></i>
                        <i class="fa fa-shopping-cart fa-4x"></i>
                    </p>
                </td>
                <td>
                    <h4 class="tour-field-title">Duration</h4>
                    <p></p>
                </td>
                <td>
                    <h4 class="tour-field-title">Themes</h4>
                    <p>Exotic</p>
                </td>
                <td>
                    <h4 class="tour-field-title">Group Size</h4>
                    <p>3 - 5</p>
                </td>
                <td>
                    <h4 class="tour-field-title">Rate</h4>
                    <p>7.2</p>
                </td>
            </tr>
        </table>
    </section>
    
    <section class="row">
        <div class="col-xs-12" style="margin:20px 0px 100px;">
            
        <h4 class="tour-field-title">Spots</h4>
        
        <span>TPE 101</span>, 
        <span>TPE 101</span>, 
        <span>TPE 101</span>
        
        </div>
        
        <div class="col-xs-12" style="margin:20px 0px 100px;">
            
            <h4 class="tour-field-title">Description of Itinerary</h4>
            
            <div style="width:inherit;word-break: break-all;">
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            </div>    
        </div>
        
    </section>
    
    <section class="row">
        
        <div id="carouselSlider" class="carousel slide col-sm-6" data-ride="carousel">
            <ol class="carousel-indicators thumb-control">
            <li data-target="#carouselSlider" data-slide-to="0" class="active"></li>
            <li data-target="#carouselSlider" data-slide-to="1"></li>
          </ol>
            
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="img-responsive" src="http://placehold.it/555x320" alt="555x320" />
              <div class="carousel-caption">
                product1
              </div>
            </div>
            <div class="item">
              <img class="img-responsive" src="http://placehold.it/555x320" alt="555x320" />
              <div class="carousel-caption">
                product2
              </div>
            </div>
          </div>
        </div>
        
        <div class="col-sm-6">
            <img class="img-responsive" src="http://placehold.it/555x320?text=Map" />
        </div>
        
    </section>
    
    
    <section class="text-center" style="margin-top:30px;">
        <button class="btn btn-lg btn-default">Close</button>
    </section>
    
    
</div>
