<div class="container">
    <ol class="breadcrumb alert alert-warning" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <li><a href="/">Home</a></li>
      <li class="active">Quickly Info building</li>
      <div class="well" style="margin-top: 10px;">
          編輯行程表單第一頁
      </div>
    </ol>

    <div class="page-header text-center">
        <h1>Be a Local Expert</h1>
        <p> as a guide and meet some friends</p>
    </div>


    <div class="row">
        <form class="form-horizontal" id="" role="form">
            
        <div class="col-sm-4 col-sm-offset-4" style="margin-top:50px;margin-bottom:100px;">
            <div class="form-group">
                <label class="col-sm-4 control-label" for="city">City</label>
                <div class="col-sm-8">
                    <select id="city" name="city" class="form-control">
                        <option value="">select</option>
                        <option value="">select</option>
                        <option value="">select</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label" for="occupation">Occupation</label>
                <div class="col-sm-8">
                    <select id="occupation" name="occupation" class="form-control">
                        <option value="">select</option>
                        <option value="">select</option>
                        <option value="">select</option>
                    </select>
                </div>
            </div>
        </div>    
        
        <div style="clear:both;"></div>
        
            <div class="form-group" style="margin-bottom: 150px;">
                <div class="col-sm-4 text-center">
                  <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                  <h2>Heading</h2>
                  <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                  <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-sm-4 text-center">
                  <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                  <h2>Heading</h2>
                  <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                  <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-sm-4 text-center">
                  <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                  <h2>Heading</h2>
                  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                  <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
                </div><!-- /.col-lg-4 -->
              </div>
            
              <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6 text-center">
                  <button type="button" class="btn btn-default" onclick="window.location='/build-account.html';">Apply(Account Building)</button>
                  &nbsp;
                  <button type="button" class="btn btn-default" onclick="window.location='/build-detail.html';">Apply(Detail Info building)</button>
                </div>
              </div>
            
        </form>
        
    </div>
    

</div>
