<div class="container">

    <div class="page-header text-center">
        <h1>Host Your tour</h1>
        <h4 class="page-subtitle">as a guide and meet some friends</h4>
    </div>

    <form class="form-horizontal" role="form">
        
        <div class="text-center" style="margin-top:50px; margin-bottom:50px;">
            <h2>Add Itinerary Name
                <span class="h2-extend">(10~50 words)</span>
            </h2>
        </div>
        
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10">
                <input class="form-control" id="" name="" />
            </div>
        </div>
        
        
        <div class="text-center" style="margin-top:50px; margin-bottom:50px;">
            <h2>Add Spots and Photos</h2>
        </div>
        
        
        <div class="form-group">
            <div class="col-sm-5">
                <div class="col-sm-6">
                <label for="inputPassword3" class="control-label">City</label>
                <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
                <div class="col-sm-6">
                <label for="inputPassword3" class="control-label">Password</label>
                  <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
            </div>
            <div class="col-sm-7" style="height: 400px;">
                <img src="//placehold.it/650x400"
            </div>
        </div>
        
        <div class="col-sm-offset-4 col-sm-4 text-center" style="margin-top:50px; margin-bottom:50px;">
            To make you tour page look better, You should upload at least 3 photoes. (the first one will be the cover photo)
        </div>
        
        <div class="col-xs-12 text-center" style="margin-top:50px;margin-bottom:50px;">
            <h2>Activities</h2>
            
            <div>
                <i class="fa fa-glass fa-4x"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa fa-coffee fa-4x"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa fa-book fa-4x"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa fa-taxi fa-4x"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa fa-yelp fa-4x"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa fa-yelp fa-4x"></i>
            </div>
            
        </div>

        <div class="col-xs-12 text-center" style="margin-top:50px; margin-bottom:50px;">
            <h2>Duration</h2>
            <div>
                <img src="http://placehold.it/80x80?text=3hrs" class="img-circle" alt="<3hrs" data-holder-rendered="true" style="width: 80px; height: 80px;" />&nbsp;&nbsp;&nbsp;&nbsp;
                <img src="http://placehold.it/80x80?text=3-5hrs" class="img-circle" alt="3-5hrs" data-holder-rendered="true" style="width: 80px; height: 80px;" />&nbsp;&nbsp;&nbsp;&nbsp;
                <img src="http://placehold.it/80x80?text=5hrs" class="img-circle" alt="" data-holder-rendered="true" style="width: 80px; height: 80px;" />
            </div>
        </div>
        
        <div class="col-xs-12 text-center" style="margin-top:50px;margin-bottom:50px;">
            <h2>Themes</h2>
            <div class="form-group">
            <input type="radio" class="form-control" name="" /> Hipster
            </div>
            <div class="form-group">
            <input type="radio" class="form-control" name="" /> Super Local
            </div> 
            <div class="form-group">
            <input type="radio" class="form-control" name="" /> Romantic
            </div> 
            <div class="form-group">
            <input type="radio" class="form-control" name="" /> Exotic
            </div> 
            <div class="form-group">
            <input type="radio" class="form-control" name="" /> Adventurous
            </div> 
        </div>
        
        <div class="col-xs-12 text-center" style="margin-top:50px;margin-bottom:50px;">
            <h2>Group Size Limitation</h2>

            <input type="number" max="0" min="100" name="min" />
            &nbsp;&nbsp; - &nbsp;&nbsp;
            <input type="number" max="50" min="200" name="max" />
        </div>
        
        <div class="col-xs-12 text-center">
            <h2>Price</h2>
            <input type="number" max="50" min="200" name="max" /> / <i class="fa fa-user"></i>
        </div>
        
        <div class="col-xs-12 text-center" style="margin-top:50px;margin-bottom:50px;">
            <h2>Description</h2>
            <div class="col-sm-offset-3 col-sm-6">
            <textarea class="form-control" rows="8"></textarea>
            </div>
        </div>
        
        <div class="col-xs-12 text-center" style="margin-top:50px;margin-bottom:50px;">
            <input type="button" name="preview" class="btn btn-warning btn-lg" onclick="window.location='/build-preview.html';" value="Preview" />
            <input type="submit" name="submit" class="btn btn-primary btn-lg" onclick="alert('server-side!');return false;"  value="Submit" />
        </div>
    </form>

    
    

</div>
