<style type="text/css">
	.display-relative{
    	position:relative;
    } 
    .class-margin{
    	margin-bottom:10px; 
    }
</style>
<div class="container">
    
    <div class="page-header">
        <h1>Expert Page</h1>
    </div>

    <div class="row clearfix">
		<div class="col-xs-12 col-sm-8 col-md-6 column">
			<img class="img-responsive" src="http://placehold.it/250x400?text=Map" />
			<div class="col-md-12 text-left">
				<h3 class="col-md-1">7.5</h3>
				<h3 class="col-md-5 col-md-offset-1">Chee Lin</h3>
			</div>
			<div class="col-md-12">
				<h4 class="col-md-4 col-md-offset-2">Designer</h4>
			</div>			
			
			<label for="Language" class="col-md-12 control-label"><h2><strong>Language</strong></h2></label>
			<div class="col-md-12">
				<h3>English/Chinese/Japanese</h3>
			</div>
			
			<div class="form-group">
				<label for="Activities" class="col-sm-3 control-label"><h2><strong>Activities</strong></h2></label>
				<div class="col-sm-12">
					<i class="col-sm-2 fa fa-coffee fa-3x"></i>
					<i class="col-sm-2 fa fa-camera fa-3x"></i>
					<i class="col-sm-2 fa fa-shopping-cart fa-3x"></i>
					<i class="col-sm-2 fa fa-area-chart fa-3x"></i>
				</div>
			</div>
		
			<label for="Interests" class="col-md-12 control-label"><h2><strong>Interests</strong></h2></label>
			<div class="col-md-12">
				<h3>Photograph/Visual/Jog</h3>
			</div>
			
			<label for="Themes" class="col-md-12 control-label"><h2><strong>Themes</strong></h2></label>
			<div class="col-md-12">
				<h3>Exotic/Romantic</h3>
			</div>
			
			<label for="Biography" class="col-md-12 control-label"><h2><strong>Biography</strong></h2></label>
			<div class="col-md-12">
				<h3><div style="width:inherit;word-break: break-all;">
			            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
					</div>
				</h3>
			</div>
		</div>
		<div class="col-md-6 column">
			<div class="row">
	        	<div class="col-md-9">
	        		<img class="img-rounded img-responsive" src="http://placehold.it/450x250" alt="450x250" />
	        	</div>
	        	<div class="col-md-3">
	        		<label class="text-left">
	        			<i class="col-md-6 fa fa-camera fa-2x"></i>
                   		<i class="col-md-6 fa fa-shopping-cart fa-2x"></i>
                    </label>
                	<label class="text-left"><h3>Hipster</h3></label>
               	 	<label class="text-left"><h3>size 3-5</h3></label>
               	 	<label class="text-left"><h4><p class="text-center btn-info">USD $500</p></h4></label>
	        	</div>	        	
	        </div>
	        <br />
	        <div class="row">
	        	<div class="col-md-9">
	        		<img class="img-rounded img-responsive" src="http://placehold.it/450x250" alt="450x250" />
	        	</div>
	        	<div class="col-md-3">
	        		<label class="text-left">
	        			<i class="col-md-6 fa fa-camera fa-2x"></i>
                   		<i class="col-md-6 fa fa-shopping-cart fa-2x"></i>
                    </label>
                	<label class="text-left"><h3>Hipster</h3></label>
               	 	<label class="text-left"><h3>size 3-5</h3></label>
               	 	<label class="text-left"><h4><p class="text-center btn-info">USD $500</p></h4></label>
	        	</div>	        	
	        </div>
	        <br />
	        <div class="row">
	        	<div class="col-md-9">
	        		<img class="img-rounded img-responsive" src="http://placehold.it/450x250" alt="450x250" />
	        	</div>
	        	<div class="col-md-3">
	        		<label class="text-left">
	        			<i class="col-md-6 fa fa-camera fa-2x"></i>
                   		<i class="col-md-6 fa fa-shopping-cart fa-2x"></i>
                    </label>
                	<label class="text-left"><h3>Hipster</h3></label>
               	 	<label class="text-left"><h3>size 3-5</h3></label>
               	 	<label class="text-left"><h4><p class="text-center btn-info">USD $500</p></h4></label>
	        	</div>	        	
	        </div>
	        <br />
	        <div class="row">
	        	<div class="col-md-9">
	        		<img class="img-rounded img-responsive" src="http://placehold.it/450x250" alt="450x250" />
	        	</div>
	        	<div class="col-md-3">
	        		<label class="text-left">
	        			<i class="col-md-6 fa fa-camera fa-2x"></i>
                   		<i class="col-md-6 fa fa-shopping-cart fa-2x"></i>
                    </label>
                	<label class="text-left"><h3>Hipster</h3></label>
               	 	<label class="text-left"><h3>size 3-5</h3></label>
               	 	<label class="text-left"><h4><p class="text-center btn-info">USD $500</p></h4></label>
	        	</div>	        	
	        </div>
	        <br />
	        <div class="row">
	        	<div class="col-md-9">
	        		<img class="img-rounded img-responsive" src="http://placehold.it/450x250" alt="450x250" />
	        	</div>
	        	<div class="col-md-3">
	        		<label class="text-left">
	        			<i class="col-md-6 fa fa-camera fa-2x"></i>
                   		<i class="col-md-6 fa fa-shopping-cart fa-2x"></i>
                    </label>
                	<label class="text-left"><h3>Hipster</h3></label>
               	 	<label class="text-left"><h3>size 3-5</h3></label>
               	 	<label class="text-left"><h4><p class="text-center btn-info">USD $500</p></h4></label>
	        	</div>	        	
	        </div>
	        <br />
	        
			<nav class="text-center">
			  <ul class="pagination">
			    <li>
			      <a href="#" aria-label="Previous">
			        <span aria-hidden="true">&laquo;</span>
			      </a>
			    </li>
			    <li><a href="#">1</a></li>
			    <li><a href="#">2</a></li>
			    <li><a href="#">3</a></li>
			    <li>
			      <a href="#" aria-label="Next">
			        <span aria-hidden="true">&raquo;</span>
			      </a>
			    </li>
			  </ul>
			</nav>
		</div>
		
	</div>

</div>
