<style type="text/css" media="screen">
    .pos-rel{ position: relative; }
	
	#idxSearch .slogen{
	    position: absolute;
	    top:250px;
	    font-size: 1.8em;
	}
	#idxSearch .form{
	    position: absolute;
        top:380px;
	}

 /* mobile指定樣式 */
@media screen and (max-width: 767px) {
    body{ font-size: 12px; }
    h1 { font-size: 1.5em; }
    h2 { font-size: 1.3em; }
    h3 { font-size: 1.1em; }
}
</style>


<section id="idxSearch" class="row">
    <div class="hidden-xs hidden-sm col-md-6 pos-rel">
        <h1 class="slogen">
        EXPERIENCE THE CITY<br />BEYOND TOURIST NORM WITH A LOCAL EXPERT
        </h1>
        
        <form id="searchForm" class="form form-inline" role="form">
          <div class="form-group">
          <div class="input-group">
              <label class="sr-only" for="city">City</label>
              <input type="text" class="form-control" id="city" placeholder="City">
              <div class="input-group-addon">@</div>
          </div>
          </div>
          <div class="form-group">
          <div class="input-group">
              <label class="sr-only" for="city">Occupation</label>
              <input type="text" class="form-control" id="Occupation" placeholder="Occupation">
              <div class="input-group-addon">@</div>
          </div>
          </div>
          <button type="submit" class="btn btn-danger">Search</button>    
        </form>
    </div>
    <div class="col-xs-12 col-md-6">
        <div id="carousel-top" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-top" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-top" data-slide-to="1"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="" src="http://placehold.it/720x320" />
              <div class="carousel-caption">&nbsp;</div>
            </div>
            <div class="item">
              <img class="" src="http://placehold.it/720x320" />
              <div class="carousel-caption">&nbsp;</div>
            </div>
          </div>
        </div>
        <br />
        <div id="carousel-down" class="hidden-xs hidden-sm carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-down" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-down" data-slide-to="1"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="" src="http://placehold.it/720x320" />
              <div class="carousel-caption">&nbsp;</div>
            </div>
            <div class="item">
              <img class="" src="http://placehold.it/720x320" />
              <div class="carousel-caption">&nbsp;</div>
            </div>
          </div>
        </div>
        
        <div class="visible-sm visible-xs">
            <h1 class="">
            EXPERIENCE THE CITY&nbsp;BEYOND TOURIST NORM WITH A LOCAL EXPERT
            </h1>
            
            <form id="searchForm" class="form-inline" role="form">
              <div class="form-group">
              <div class="input-group">
                  <label class="sr-only" for="city">City</label>
                  <input type="text" class="form-control" id="city" placeholder="City">
                  <div class="input-group-addon">@</div>
              </div>
              </div>
              <div class="form-group">
              <div class="input-group">
                  <label class="sr-only" for="city">Occupation</label>
                  <input type="text" class="form-control" id="Occupation" placeholder="Occupation">
                  <div class="input-group-addon">@</div>
              </div>
              </div>
              <button type="submit" class="btn btn-danger">Search</button>    
            </form>
        </div>
    </div>    
</section>

<section id="idxPopularItineraries" class="row" style="clear:both;">
    <h3 class="text-center">Popular Itineraries</h3>
    <div style="clear:both;"></div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x300" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
</section>

<section id="idxFeatureLocalExperts" class="hidden-xs row" style="clear:both;">
    <h3 class="text-center">New Itineraries</h3>
    <div style="clear:both;"></div>
    <section class="row">
        <aside class="col-sm-4">
            <div class="thumbnail">
              <img src="http://placehold.it/300x300" alt="thumbnail" />
              <div class="caption row">
                <div class="col-xs-6">
                <h4>Thumbnail label</h4>
                <p>descripton</p>
                </div>
                <p class="col-xs-6 text-right" style="margin-top:20px;">
                    <a href="#" class="btn btn-primary" role="button">icon</a> 
                </p>
              </div>
            </div>
            <div class="thumbnail">
              <img src="http://placehold.it/300x300" alt="thumbnail" />
              <div class="caption row">
                <div class="col-xs-6">
                <h4>Thumbnail label</h4>
                <p>descripton</p>
                </div>
                <p class="col-xs-6 text-right" style="margin-top:20px;">
                    <a href="#" class="btn btn-primary" role="button">icon</a> 
                </p>
              </div>
            </div>
        </aside>
        <article class="col-sm-8">
            <div class="thumbnail">
          <img src="http://placehold.it/700x718" alt="thumbnail" />
          <div class="caption row">
            <div class="col-xs-6">
            <h4>Thumbnail label</h4>
            <p>descripton</p>
            </div>
            <p class="col-xs-6 text-right" style="margin-top:20px;">
                <a href="#" class="btn btn-primary" role="button">icon</a> 
            </p>
          </div>
             </div>
        </article>
    </section>
</section>

<section id="idxNewItineraries" class="row" style="clear:both;">
    <h3 class="text-center">Feature Local Experts</h3>
    <div style="clear:both;"></div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x600" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="col-xs-6 col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x600" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
    <div class="hidden-xs col-sm-4">
    <div class="thumbnail">
      <img src="http://placehold.it/300x600" alt="thumbnail" />
      <div class="caption row">
        <div class="col-xs-6">
        <h4>Thumbnail label</h4>
        <p>descripton</p>
        </div>
        <p class="col-xs-6 text-right" style="margin-top:20px;">
            <a href="#" class="btn btn-primary" role="button">icon</a> 
        </p>
      </div>
    </div>
    </div>
</section>


<script>
$(function(){
    $('#carousel-down').each(function(){
        $(this).carousel();
        var carousel = $(this).data('carousel');
        carousel.pause();
        // At first, reverse the order of the items in the carousel because we're moving backwards
        $(this).find('> .carousel-inner > .item:not(:first-child)').each(function() {
            $(this).prependTo(this.parentNode);
        });
        // Override the bootstrap carousel prototype function, adding a different one won't work (it'll work only for the first slide)
        carousel.cycle = function (e) {
            if (!e) this.paused = false
            if (this.interval) clearInterval(this.interval);
            this.options.interval
            && !this.paused
            && (this.interval = setInterval($.proxy(this.prev, this), this.options.interval))
            return this;
        };

        carousel.cycle();
    });
});
</script>