<div class="container">
    <ol class="breadcrumb alert alert-warning" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <li><a href="#">Home</a></li>
      <li class="active">Logout</li>
      <div class="well" style="margin-top: 10px;">
          任何已登入帳號頁面皆可連結
      </div>
    </ol>

    <div class="page-header">
        <h1>Logout</h1>
    </div>

    

</div>
