<div class="container">
    
    <div class="page-header">
        <h1>Request Confirm</h1>
    </div>
	<div class="col-md-12 column " align="center">
		<section class="feature-confirm feature-confirm-img class-margin10" style="width:600px">
	        <img class="img-rounded img-responsive" src="http://placehold.it/600x300" alt="600x300" />		        
	        <div class="feature-confirm-expert">
	            <img src="http://placehold.it/80x120/285E8E" />
	        </div>
    	</section>
    	
    	<h3 class="text-center">USD ＄550</h3>
    	<h3 class="text-center">DATE: 2014.11.24</h3>
    	<h3 class="text-center"><img src="http://placehold.it/40x60/285E8E" />*2</h3>
    	<h3 class="text-center class-margin10">Cancellation Policy:Moderate</h3>
    	
    	<div class="page-header"></div>
    	
    	<h3 class="col-sm-offset-3 col-md-6 slogen">
	        You will only be changed if the host accepts your request. They'll have 24 hours to reply. If the host declines or does not respond, no charge is made.
	    </h3>
	    
	    <div class="col-sm-offset-2 col-md-8">
          <button type="submit" class="btn btn-default">Bookies History </button>
          <button type="submit" class="btn btn-danger col-sm-offset-1">Book more</button>
        </div>
	</div>	
    

</div>
