<style type="text/css">
    .feature{ position: relative; }
    .feature-img{  }
    .feature-expert{ 
        position: absolute;
        bottom: -50px;
        left: 5px;
    }
    
    .tour-name{
        margin-left:5em;
        margin-top:-10px;
    }
    
    .tour-name span{
        margin-left:3em;
        font-size: 0.4em;
    }
    
    .table-fix-border tr td{ border:none !important; }
    .tour-field-title{
        font-size: 2em;
        color:#969696;
    }
    
    .tour-eminfo{
        position:relative;
        top:15px;
        left:10px;
        z-index:50;
        background-color: #333;
        width: 110%;
        height: 120px;
        color: #FFF;
        font-size: 2.5em;
        padding-left:10px;
    }
        .eminfo-desc{ font-size: 0.7em; margin-right:25px; }
        .eminfo-price{ font-size: 1.2em;}
    
    .thumb-control{
        bottom: 0px;
        left:0px; 
    }   
    
    .display-relative{
    	position:relative;
    } 
    
    .class-width{
    	width:50%
    }
    .class-margin{
    	margin-bottom:10px; 
    }
</style>
<div class="container">
    
    <div class="page-header">
        <h1>Request</h1>
    </div>
	<div class="row clearfix">
		<div class="col-xs-12 col-sm-8 col-md-6 column">
			<div class="row display-relative">
			<h3 class="slogen">
	        You will only be changed if the host accepts your request. They'll have 24 hours to reply. If the host declines or does not respond, no charge is made.
	        </h3>
	        <textarea id="request" name="request" class="form-control" rows="8"></textarea>
	        
           	</div>
            <br /><br />
	        <div class="row display-relative">
	        	<h4 class="col-md-3">2nd choice</h4>
	        	
	        	<div class="col-md-3">
	        		<div class="input-group date ">
	                    <input type="text" class="form-control" id="2ndchoice"/>                    
	                </div>
	            </div>
                <h4 class="col-md-3">3nd choice</h4>
	        	
	        	<div class="col-md-3">
	        		<div class="input-group date ">
	                    <input type="text" class="form-control" id="3ndchoice"/>
	                    
	                </div>
	        	</div>	        	
	        </div>
	        <br />
	        <div class="page-header"></div>
	        <br />
	        <br />
	        <div class="col-sm-offset-4 col-sm-10">
	          <button type="submit" class="btn btn-danger">Paypal</button>
	          <button type="submit" class="btn btn-default col-sm-offset-1">Credit Card</button>
	        </div>
		</div>
		<div class="col-md-6 column">
			<section class="feature feature-img class-margin" >
		        <img class="img-rounded img-responsive" src="http://placehold.it/600x300" alt="600x300" />		        
		        <div class="feature-expert">
		            <img src="http://placehold.it/80x120/285E8E" />
		            <h4 class="text-center">Howie young</h4>
		        </div>
	    	</section>
	    	
	    	<h3 class="text-center">USD ＄550</h3>
	    	<h3 class="text-center">DATE: 2014.11.24</h3>
	    	<h3 class="text-center"><img src="http://placehold.it/40x60/285E8E" />*2</h3>
	    	<h3 class="text-center class-margin">Cancellation Policy:Moderate</h3>
	    	
	    	<form id="checkForm" class="form-horizontal class-margin" role="form">
				<div class="row">
					<label class="col-md-4" for="promote"><h4>Promote Code:</h4></label>
					<div class="col-md-8">
						<input type="text" class="form-control col-md-6 class-width" id="promote" placeholder="promote">
						<button type="submit" class="btn btn-primary col-md-offset-1 col-md-4">Check</button>
					</div>
				</div>			
			</form>	
			
		    <div class="page-header class-margin"></div>
			    <div class="row">
			    	<h2 class="col-md-4">Total</h2>
			    	<h2 class="col-md-4 col-md-offset-4"><strong>USD $1000</strong></h2>
			    	
			    </div>
		   </div>
		</div>		
	</div>
    
</div>
<script type="text/javascript">
$("#2ndchoice, #3ndchoice").datetimepicker({
			pickTime : false
		});
</script>